ca_cert_path: /usr/local/share/ca-certificates/foundry-appliance-root-ca.crt
identity:
    base_url: https://foundry.local/identity
    token_endpoint: connect/token
    jwks_endpoint: .well-known/openid-configuration/jwks
    client_id: gamebrain-client
    client_secret: 7e972ec6610b49dab492a92ec3d7f5cd
    jwt_audience: gamebrain-api
    jwt_issuer: https://foundry.local/identity
    token_user: administrator@foundry.local
    token_password: foundry
topomojo:
    base_api_url: https://foundry.local/topomojo/api/
gameboard:
    base_gb_url: https://foundry.local/gameboard/api/
db:
    connection_string: postgresql+psycopg2://gamebrain:gamebrain@127.0.0.1:5432/gamebrain
