app_root_prefix: /
ca_cert_path: /usr/local/share/ca-certificates/foundry-appliance-root-ca.crt
gamebrain_admin_api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
identity:
  base_url: https://foundry.local/identity
  token_endpoint: connect/token
  jwks_endpoint: .well-known/openid-configuration/jwks
  client_id: gamebrain-client
  client_secret: 7e972ec6610b49dab492a92ec3d7f5cd
  jwt_audiences:
    gamebrain_api_unpriv: gamebrain-api-unpriv
    gamebrain_api_priv: gamebrain-api-priv
    gamestate_api: gamestate-api
  jwt_issuer: https://foundry.local/identity
  token_user: administrator@foundry.local
  token_password: foundry
topomojo:
  base_api_url: https://foundry.local/topomojo/api/
  x_api_key: xaFmE0_YIo8QjDszdh0L79ySlpI79KfA
  x_api_client: user-bot-test
gameboard:
  base_url: https://foundry.local/gameboard/
  base_api_url: https://foundry.local/gameboard/api/
db:
  connection_string: postgresql+asyncpg://gamebrain:gamebrain@127.0.0.1:5432/gamebrain
  drop_app_tables: true
  echo_sql: false
game:
  gamespace_duration_minutes: 30
  event_actions:
    - event_message_partial: "Mission 1"
      action:
        action_type: change-net
        vm_name: ubuntu
        new_net: bridge-net
    - event_message_partial: "Mission 2"
      action:
        action_type: dispatch
        vm_name: ubuntu
        command: touch /home/tmtest/it-worked
  antenna_vm_name: "extend_antenna_test"
  grading_vm_name: "challenge-server"
  grading_vm_file_path: "/home/user/challengeServer/custom_scripts/requestGrade.py"
  challenge_tasks:
    - task_id: "redradr4"
      vm_name: "pirate-attacker"
      file_path: "/home/user/LanguageFile"
    - task_id: "exoarch6"
      vm_name: "station-scada-system"
      file_path: "/home/user/atmosphere"
    - task_id: "cllctn6"
      vm_name:  "museum-approach"
      file_path: "/home/user/audit"
  final_destination_name: "final"
  final_destination_file_path: "/home/user/challengeServer/custom_scripts/final_goal"
  gamestate_test_mode: false
  game_id: f63c8e41fd994e16bad08075dd2a666c
  headless_client_urls:
    "server-1": "https://foundry.local/gameserver/1"
    "server-2": "https://foundry.local/gameserver/2"
profiling: false